name: Generate game info

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  get_info:
    uses: 8bitDream/AmiiboGamelistGenerator/.github/workflows/game_info.yml@main
    with:
      repo: 8bitDream/AmiiboGamelistGenerator
      repo-ref: main

  report:
    runs-on: ubuntu-latest
    needs: [get_info]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
            ref: dev

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: games_info
          path: database/

      - name: Commit json files
        shell: pwsh
        run: |
          git config --local user.name 'AmiiboAPI (Automated)'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull origin dev
          git add -A database/games_info.json
          if(git commit -m "[Automated] Update: $(git diff --name-only --staged)") {
            git push
          }
