name: Update json
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update last-updated.json
        run: |
          python3 last_updated.py

      - name: Update sha1sum.json
        run: |
          python3 sha1sum.py

      - name: Commit json files
        run: |
          git config --local user.name 'AmiiboAPI (Automated)'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A sha1sum.json last-updated.json
          if git commit -m "[Automated] Update: $(git diff --name-only --staged)"; then
            git push
          fi
